### PR TITLE
Added option 'Use build-in icons'.

### PR DESCRIPTION
**Pull request by SuperMeowBro**
Hi, 

i have added an additional option 'Use build-in icons'. So the user can choose if he wants to use build-in archlinux icons or icons from active icon theme.

If you like it, it would be cool if you accept this pull request.

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
I wonder, if we can do this automatically by checking if icons exists in theme ...

**Comment by SuperMeowBro** [comment]
We could do it automatically by prefering icons from systems icon theme(?), but then the user cannot choose anymore, if he wants to use the build-in archlinux-branded icons or generic icons from systems icon theme.

**Comment by RaphaelRochet** [comment]
Yes that's good idea. Preferring theme icon, and optionally enforce built-in icons.

**Comment by RaphaelRochet** [comment]
I will try to do this small change quickly and close this PR.

**Comment by RaphaelRochet** [comment]
Merged manually ( 93c6602 e84a1eb  d82291a )

Could you try latest master and tell me if it works well ?

**Comment by SuperMeowBro** [comment]
Hi, yes it works for me well!

**Comment by RaphaelRochet** [comment]
Nice. Thanks for the PR and the feedback :+1:

**Pull request closed without merging**
