### PR TITLE
Create arch-update.po

### PR DESCRIPTION
**Pull request by trazalca**

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
You don't want this to be merged ?

**Comment by trazalca** [comment]
Sorry... i'm trying to understand how i have to do, sorry!!! may be you can help me please?

**Comment by RaphaelRochet** [comment]
Ah you were close : make a pull request by comparing my master branch to yours. It should include both po and mo files. Then wait for me to review the pull request.

**Comment by trazalca** [comment]
I'll try... thanks!

**Comment by RaphaelRochet** [comment]
Please make an effort to better describe your commits/request (i.e : Work on Italian translation)
Thanks

**Pull request closed without merging**
