### PR TITLE
Added option to change command used to check for updates.

### PR DESCRIPTION
**Pull request by yitzchak**
Using a script such as `{ checkupdates; cower -qbu; } | sort` will check the AUR also.

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
Please see discussion on issue #14.
I'd prefer to provide a list of -kind of- supported update checks, like yaourt/pacaur/cower/packagekit ... with update now command and update check command linked.

**Comment by yitzchak** [comment]
What about a drop-down with suggestions and leaving the ability to override with the user's own command line? I am using the extension as a notifier replacement for pamac since it uses the gnome legacy tray. In this case there isn't a straightforward linked command set since pamac is GUI only (I think). `cower -qbu` is then used only to check for updates, not install them.

**Comment by benneti** [comment]
i think this would be nice, because like this the user could choose wich command to use and the extension would not depend on additional packages

**Comment by RaphaelRochet** [comment]
Okay then ! I will review the commit and include it in next release. Expect it this week.

**Comment by benneti** [comment]
very nice, thank you :+1:

**Comment by RaphaelRochet** [comment]
Merged in commit c9ac6d9eb0080861f6117bba6c4691378ae94d0b with a few changes

**Pull request closed without merging**
