### PR TITLE
Update German strings

### PR DESCRIPTION
**Pull request by bezcitu**
Added one string and fixed several strings according to German spelling rules.
Maybe one should also remove all "#, fuzzy" markers, because those strings are shown in English although all other strings are in German.

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
It's up to you to remove the fuzzy indicator on strings. In poedit it's as easy as a toggle button in the toolbar.

**Comment by bezcitu** [comment]
@RaphaelRochet 
I'm not quite sure what these fuzzy indicators do …

**Comment by RaphaelRochet** [comment]
Fuzzy indicators means 'automatically translated ; need confirmation'. If the translation is good then remove the fuzzy indicator.

**Comment by bezcitu** [comment]
@RaphaelRochet 
Thanks for explaining it. I removed them since the translated strings should be fine.

**Comment by RaphaelRochet** [comment]
Nice, thanks

**Pull request merged**
